### ISSUE TITLE
The state of midi 2.0 on rust?

### ISSUE THREAD

**Issue by laenzlinger** [m-hilgendorf/midi20#1]
Since now MIDI 2.0 looks to get some traction (https://www.midi.org/midi-articles/details-about-midi-2-0-midi-ci-profiles-and-property-exchange) I was wondering what the state of MIDI 2.0 on rust.

I came across this crate and wanted to ask about the future of it?

**Comment by m-hilgendorf** [comment]
Hi! Sorry for the long delay in replying. 

This crate is a translation of the MIDI 2.0 spec into Rust datatypes. It's not perfect and I plan to change it to a new zero-copy based design. 

At the time that I wrote it, key parts of the spec were not published. That has changed, so there's enough information available to go out and come up with an abstraction and implementation for things like CI. 

There are two limiting factors to going beyond this crate, which are software OS support (I develop on Linux, and MIDI2 support was just mainlined today - so it will be a bit before users don't have to manually build and update their kernels), and lack of hardware. When I can buy a USB MIDI 2 device, I'll be able to do more than software tests with virtual midi devices and MIDI 1 compatible messages. 

If you want to use MIDI in Rust today, use [midir](https://github.com/Boddlnagg/midir). 

I am still interested in this, and contributions to this crate are welcome.
