### ISSUE TITLE
Groupless messages

### ISSUE THREAD

**Issue by ulzu** [m-hilgendorf/midi20#9]
2023 May specification has introduced the notion of Groupless messages.
> Added the notion of Groupless messages. Some UMP Message Types are not sent to a specific Group. These messages are intended to be processed by the MIDI Endpoint.

This breaks the `Message` trait by splitting it into two kinds: Group and Groupless messages.

Currently, messages of type `0x0` `Utility` and `0xf` `UmpStream` are Groupless.
> Utility messages (Message Type 0x0) are now Groupless. Group field is changed to Reserved.

_Sidenote_:
It appears that this change is associated with a definition of four groups of destinations for UMP messages, as presented in the Appendix H of M2-104 specification. Groupless messages are addressed to UMP Stream destination. Group messages are addressed to UMP Group and Channel destinations. Some MIDI-CI messages are addressed to Function block destinations.

**Comment by m-hilgendorf** [comment]
Since the group is reserved then there's no harm in reading the group nibble. As we add methods for building messages we will omit the `group` field for utility and UMP stream messages.
